### ISSUE TITLE
Nothing is found or even searched for, cannot get requests from overseer

### ISSUE THREAD

**Issue by activ** [mplewis/coaxist#26]
**What part of the Quick Start guide are you stuck on?**
Got it installed, but it does not actually try to search for anything.
Using all debrid for this setup

**What do you see in the logs?**

```
[04:45:39.557] ERROR (673): failed to fetch Overseerr requests
    errors: [
      {
        "code": "invalid_type",
        "expected": "string",
        "received": "null",
        "path": [
          "externalIds",
          "imdbId"
        ],
        "message": "Expected string, received null"
      }
    ]
```

**What problem are you encountering?**
Keep getting that message and no search is ever started, not even for things in the plex watch list. There are things in the wanted list in overseer so it's not empty.

Nothing, start the application and the error start showing up in the log and that is it, it never searches for anything as far as I can tell.

**Server environment (please complete the following information):**

Running in Docker on Debian
Firefox

**Additional context**
Tell me what to do or test for.
Here is my docker info:
```
version: "2.1"
services:
  coaxist:
    image: mplewis/coaxist:latest
    container_name: coaxist


    cap_add:
      - SYS_ADMIN
    volumes:
      - /appdata/coaxist/config:/config
      - /appdata/coaxist/transcode:/transcode
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/dri:/dev/dri
      - /dev/fuse:/dev/fuse
    ports:
      - 5055:5055
      - 32400:32400
    privileged: true
    restart: unless-stopped
```
